### ISSUE TITLE
Tileserver example in documentation not working

### ISSUE THREAD

**Issue by rburhum** [locationtech-labs/geopyspark#184]
It looks that there is an error with `geopyspark.geotrellis.catalog.read_value`

Repro:

- Follow directions to create catalog in temp as described here https://geopyspark.readthedocs.io/en/latest/greyscale_ingest_example.html 
This works, the expected file structure gets created in /tmp/

- Create tile server as described here:  https://geopyspark.readthedocs.io/en/latest/greyscale_tile_server_example.html#

Please note that it should say use `Pillow` not `PIL` since PIL hasn't been supported forever and it doesn't work on Python 3. We probably need to correct that in the docs.

Fetch a tile that covers the area and you will get an error:
```bash
rburhum@peru:~$ curl http://localhost:5000/6/47/31.png
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
rburhum@peru:~
```

The server stack trace reveals:
```bash
(spark) rburhum@peru:/tmp$ python server.py
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
17/05/08 19:32:25 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)



[2017-05-08 19:32:31,960] ERROR in app: Exception on /6/47/31.png [GET]
Traceback (most recent call last):
  File "/Users/rburhum/.virtualenvs/spark/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rburhum/.virtualenvs/spark/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rburhum/.virtualenvs/spark/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rburhum/.virtualenvs/spark/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/rburhum/.virtualenvs/spark/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rburhum/.virtualenvs/spark/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 24, in tile
    y)
  File "/Users/rburhum/.virtualenvs/spark/lib/python3.6/site-packages/geopyspark-0.1.0-py3.6.egg/geopyspark/geotrellis/catalog.py", line 274, in read_value
    zdt)
  File "/usr/local/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/usr/local/spark/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 319, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o26.readTile.
: geotrellis.spark.io.package$AttributeNotFoundError: Attribute metadata not found for layer Layer(name = "python-ingest", zoom = 6)
	at geotrellis.spark.io.file.FileAttributeStore.read(FileAttributeStore.scala:62)
	at geotrellis.spark.io.AttributeCaching$$anonfun$cacheRead$1.apply(AttributeCaching.scala:27)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
	at geotrellis.spark.io.AttributeCaching$class.cacheRead(AttributeCaching.scala:27)
	at geotrellis.spark.io.file.FileAttributeStore.cacheRead(FileAttributeStore.scala:36)
	at geotrellis.spark.io.BlobLayerAttributeStore$class.readHeader(AttributeStore.scala:76)
	at geotrellis.spark.io.file.FileAttributeStore.readHeader(FileAttributeStore.scala:36)
	at geopyspark.geotrellis.io.ValueReaderWrapper.getValueClass(ValueReaderFactory.scala:35)
	at geopyspark.geotrellis.io.ValueReaderWrapper.readTile(ValueReaderFactory.scala:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)

127.0.0.1 - - [08/May/2017 19:32:31] "GET /6/47/31.png HTTP/1.1" 500 -
```

**Comment by jbouffard** [comment]
Thanks for pointing out the distinction between `PIL` and `Pillow`. I didn't realize the difference between the two were so great. I'll update the docs soon.

As for the issue with retrieving the tile, it appears that you're trying to access a tile that doesn't exist. When I looked at the attributes for the 6th zoom level, the bounds were `minKey(46, 30), maxKey(46, 31)`.

When I do `curl -L http://localhost:5000/6/46/30.png -o curled.png` or `curl -L http://localhost:5000/6/46/31.png -o curled.png` they both work.

**Comment by rburhum** [comment]
Mmm. If it works for you, there must be an error on my end. I get a 500.

```
rburhum@peru:~$ curl http://localhost:5000/6/46/30.png
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
rburhum@peru:~$
```

**Comment by jbouffard** [comment]
Could you try switching to another port to see if it works then? You'd just have to change `app.run` to `app.run(port=...)` in the `tile_server` example. Also, you could try `lsof -i:5000` to kill any process using port 5000 and then start up the server again.

**Comment by rburhum** [comment]
No zombie processes, but I still switched to port 9001. Same error. I have a feeling that it may be to how the first program wrote the files on disk perhaps? The files are there, but not sure what format they are in.
