### ISSUE TITLE
Calling `masked` causes zoom_level to disappear

### ISSUE THREAD

**Issue by lossyrob** [locationtech-labs/geopyspark#193]
I had some code like this
```python
def ingest_layer(layer_name, path):
    rdd = get(geopysc, SPATIAL, path, maxTileSize=512, numPartitions=20)
    metadata = rdd.collect_metadata(tile_size=512)
    metadata['cellType'] = "int8"
    laid_out = rdd.tile_to_layout(metadata)
    reprojected = laid_out.reproject("EPSG:3857", scheme=ZOOM)
    for layer_rdd in reprojected.pyramid(reprojected.zoom_level, 0):
        write(catalog_uri, layer_name, layer_rdd)
```

I changed it to use a mask:
```python
def ingest_layer(layer_name, path):
    rdd = get(geopysc, SPATIAL, path, maxTileSize=512, numPartitions=20)
    metadata = rdd.collect_metadata(tile_size=512)
    metadata['cellType'] = "int8"
    laid_out = rdd.tile_to_layout(metadata)
    reprojected = laid_out.reproject("EPSG:3857", scheme=ZOOM)
    masked = reprojected.mask([chatta_poly])
    for layer_rdd in masked.pyramid(masked.zoom_level, 0):
        write(catalog_uri, layer_name, layer_rdd)
```

Unexpectedly it broke with this error:

```
Py4JError                                 Traceback (most recent call last)
<ipython-input-18-3b4f37105079> in <module>()
      1 for layer in layers:
      2     print("Ingesting %s at %s" % (layer, layers[layer]))
----> 3     ingest_layer(layer, layers[layer])

<ipython-input-17-9190d008dba9> in ingest_layer(layer_name, path)
      7     masked = reprojected.mask([chatta_poly])
      8     print(type(masked))
----> 9     for layer_rdd in masked.pyramid(masked.zoom_level, 0):
     10         write(catalog_uri, layer_name, layer_rdd)

/home/hadoop/.local/lib/python3.4/site-packages/geopyspark/geotrellis/rdd.py in pyramid(self, start_zoom, end_zoom, resample_method)
    546             raise ValueError("Tiles must have a col and row count that is a power of 2")
    547 
--> 548         result = self.srdd.pyramid(start_zoom, end_zoom, resample_method)
    549 
    550         return [TiledRasterRDD(self.geopysc, self.rdd_type, srdd) for srdd in result]

/usr/local/spark-2.1.0-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1131         answer = self.gateway_client.send_command(command)
   1132         return_value = get_return_value(
-> 1133             answer, self.gateway_client, self.target_id, self.name)
   1134 
   1135         for temp_arg in temp_args:

/usr/local/spark-2.1.0-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    321                 raise Py4JError(
    322                     "An error occurred while calling {0}{1}{2}. Trace:\n{3}\n".
--> 323                     format(target_id, ".", name, value))
    324         else:
    325             raise Py4JError(

Py4JError: An error occurred while calling o54.pyramid. Trace:
py4j.Py4JException: Method pyramid([null, class java.lang.Integer, class java.lang.String]) does not exist
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:326)
	at py4j.Gateway.invoke(Gateway.java:272)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)
```

Seems like the masked rdd lost the zoom_level.

**Comment by jbouffard** [comment]
It appears that the `mask` methods for both `SpatialTiledRasterRDD` and `TemporalTiledRasterRDD` returns a new instance of its respective class with a `zoomLevel` of `None`; regardless if the instance calling this method had one or not.

See [SpatialTiledRasterRDD's mask method](https://github.com/locationtech-labs/geopyspark/blob/master/geopyspark-backend/geotrellis/src/main/scala/geopyspark/geotrellis/TiledRasterRDD.scala#L317) and [TiledRasterRDD's mask method](https://github.com/locationtech-labs/geopyspark/blob/master/geopyspark-backend/geotrellis/src/main/scala/geopyspark/geotrellis/TiledRasterRDD.scala#L380)
