### ISSUE TITLE
to_numpy_rdd() gives dicts as keys, but these are not hashable -> not joinable

### ISSUE THREAD

**Issue by lossyrob** [locationtech-labs/geopyspark#227]
We should be able to easily join numpy RDDs. This code:

```python
fcn = read(geopysc,
           SPATIAL,
           catalog_uri,
           "isprs-potsdam-fcn-predictions",
           19, 
           numPartitions=100).to_numpy_rdd()
fcndsm = read(geopysc,
              SPATIAL,
              catalog_uri,
              "isprs-potsdam-fcndsm-predictions",
              19, 
              numPartitions=100).to_numpy_rdd()
labels = read(geopysc,
              SPATIAL,
              catalog_uri,
              label_layer_name,
              19, 
             numPartitions=100).to_numpy_rdd()

def mapper(v):
    ((fcn_tile, fcndsm_tile), label_tile) = v._2
fcn.join(fcndsm).join(labels).map(mapper).count()
```

throws this exception:

```
ob aborted due to stage failure: Task 0 in stage 14.0 failed 1 times, most recent failure: Lost task 0.0 in stage 14.0 (TID 229, localhost, executor driver): org.apache.spark.api.python.PythonException: Traceback (most recent call last): +details
Job aborted due to stage failure: Task 0 in stage 14.0 failed 1 times, most recent failure: Lost task 0.0 in stage 14.0 (TID 229, localhost, executor driver): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/usr/local/spark-2.1.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.py", line 174, in main
    process()
  File "/usr/local/spark-2.1.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.py", line 169, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/usr/local/spark-2.1.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/rdd.py", line 2407, in pipeline_func
  File "/usr/local/spark-2.1.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/rdd.py", line 346, in func
  File "/usr/local/spark-2.1.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/rdd.py", line 1912, in combine
  File "/usr/local/spark-2.1.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/shuffle.py", line 238, in mergeValues
    d[k] = comb(d[k], v) if k in d else creator(v)
TypeError: unhashable type: 'dict'

	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:193)
	at org.apache.spark.api.python.PythonRunner$$anon$1.<init>(PythonRDD.scala:234)
	at org.apache.spark.api.python.PythonRunner.compute(PythonRDD.scala:152)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.api.python.PairwiseRDD.compute(PythonRDD.scala:390)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
```

**Comment by lossyrob** [comment]
Not sure if this is a bug, more than a design consideration

**Comment by jbouffard** [comment]
`dict`s aren't hashable in Python, so that makes sense. It could be that PySpark uses `dict`s to keep track of values during the join, and it was trying to make `V` of the tuple a key. However, I'll have to look into this more.

We'll need to do some redesigning then.

**Comment by lossyrob** [comment]
It's the `K` of a numpy array a dict? `{ 'col' : 1, 'row' : 2 }`

**Comment by jbouffard** [comment]
Yeah, that's also a `dict` as well. Sorry, I misread that error message. We made it `dict` so that we could retain the `no_data_value`.

One solution to this problem is using `namedtuple`s instead of `dict`s to represent `Tile`, `PorjectedExtent`, `SpatialKey`, etc. We already do this for certain data structures https://github.com/locationtech-labs/geopyspark/blob/master/geopyspark/geotrellis/__init__.py#L54

The only down side to using `namedtuple`s is that there will be a bit more overhead when serializing/deserializing the RDD, and it would require reworking the back end somewhat.

**Comment by lossyrob** [comment]
We only need the key to be hashable. The value can remain a dict. So no
need to touch Tile, but names tuples for the key types you listed make
sense. Deserialization can still happen to a dict, just needs one more map
to map the keys to the names tuples.
