### ISSUE TITLE
Methods For Certain TiledRasterLayers Do Not Work

### ISSUE THREAD

**Issue by jbouffard** [locationtech-labs/geopyspark#350]
There seems to be an issue when working with certain `TiledRasterLayer`s that causes them to fail when using certain methods. The problems that arise seem to only happen for `TiledRasterLayer`s which were made from Python `RDD`s.

For example, using this `TiledRasterLayer`:

```python
data = np.array([[
    [1.0, 1.0, 1.0, 1.0, 1.0],
    [1.0, 1.0, 1.0, 1.0, 1.0],
    [1.0, 1.0, 1.0, 1.0, 1.0],
    [1.0, 1.0, 1.0, 1.0, 1.0],
    [1.0, 1.0, 1.0, 1.0, 0.0]]], dtype=float)

layer = [(SpatialKey(row=0, col=0), Tile(cells=data, cell_type='FLOAT', no_data_value=-1.0)),
         (SpatialKey(row=1, col=0), Tile(cells=data, cell_type='FLOAT', no_data_value=-1.0)),
         (SpatialKey(row=0, col=1), Tile(cells=data, cell_type='FLOAT', no_data_value=-1.0)),
         (SpatialKey(row=1, col=1), Tile(cells=data, cell_type='FLOAT', no_data_value=-1.0))]

rdd = pysc.parallelize(layer)

extent = Extent(0.0, 0.0, 33.0, 33.0)
layout = TileLayout(2, 2, 5, 5)
bounds = Bounds(SpatialKey(col=0, row=0), SpatialKey(col=1, row=1))
layout_definition = LayoutDefinition(extent, layout)

metadata = Metadata(
    bounds=bounds,
    crs='+proj=longlat +datum=WGS84 +no_defs ',
    cell_type='float32ud-1.0',
    extent=extent,
    layout_definition=layout_definition)

tiled_layer = TiledRasterLayer.from_numpy_rdd(pysc=pysc, layer_type=LayerType.SPATIAL, numpy_rdd=rdd, metadata=metadata)
```

Will throw an error when trying to use `reproject`:

```python
tiled_layer.reproject(target_crs=3857)

Py4JJavaError: An error occurred while calling o40.reproject.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 4.0 failed 1 times, most recent failure: Lost task 1.0 in stage 4.0 (TID 7, localhost, executor driver): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py", line 163, in main
    func, profiler, deserializer, serializer = read_command(pickleSer, infile)
  File "/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py", line 54, in read_command
    command = serializer._read_with_length(file)
  File "/usr/local/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 169, in _read_with_length
    return self.loads(obj)
  File "/usr/local/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 451, in loads
    return pickle.loads(obj, encoding=encoding)
ImportError: No module named 'geopyspark.geotrellis.protobufserializer'

	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:193)
	at org.apache.spark.api.python.PythonRunner$$anon$1.<init>(PythonRDD.scala:234)
	at org.apache.spark.api.python.PythonRunner.compute(PythonRDD.scala:152)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at geotrellis.spark.ContextRDD.compute(ContextRDD.scala:39)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

This does not happen though when the `TiledRasterLayer` is created from a `RasterLayer`:

```python
layer = geotiff.get(pysc, "spatial", "/home/jacob/econic.tif")
t_layer = layer.to_tiled_layer()
t_layer.reproject(target_crs=3857) 
```

From the above error message, this appears to be a serialization error of some sort.

**Comment by jbouffard** [comment]
After further investigation, this isn't actually a serialization issue. Rather, it is about not finding the `protobufserializer` module in general. This was never picked up in the tests because they were always ran from the root of the project, so `protobufserializer` was in the location the import said it would be.

**Comment by jbouffard** [comment]
After even more investigating, it turns out this is a problem with my system and not GeoPySpark as a whole. Thus, I'm closing this issue.
