### ISSUE TITLE
 Operation.ASPECT and  Operation.SLOPE  trigger match exception on Neighborhood

### ISSUE THREAD

**Issue by echeipesh** [locationtech-labs/geopyspark#353]
```log
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-16-5beba2928501> in <module>()
      2 aspect_rdd = elev_tiled_rdd.focal(
      3     Operation.ASPECT,
----> 4     Neighborhood.SQUARE, 1)

~/proj/geopyspark/geopyspark/geotrellis/layer.py in focal(self, operation, neighborhood, param_1, param_2, param_3)
    927 
    928             srdd = self.srdd.focal(operation, nb(neighborhood).value,
--> 929                                    float(param_1), float(param_2), float(param_3))
    930 
    931         elif not neighborhood and operation == Operation.SLOPE.value or operation == Operation.ASPECT.value:

/usr/local/Cellar/apache-spark/2.1.1/libexec/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1131         answer = self.gateway_client.send_command(command)
   1132         return_value = get_return_value(
-> 1133             answer, self.gateway_client, self.target_id, self.name)
   1134 
   1135         for temp_arg in temp_args:

/usr/local/Cellar/apache-spark/2.1.1/libexec/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    317                 raise Py4JJavaError(
    318                     "An error occurred while calling {0}{1}{2}.\n".
--> 319                     format(target_id, ".", name), value)
    320             else:
    321                 raise Py4JError(

Py4JJavaError: An error occurred while calling o34.focal.
: scala.MatchError: Square (of class java.lang.String)
	at geopyspark.geotrellis.GeoTrellisUtils$.getNeighborhood(GeoTrellisUtils.scala:54)
	at geopyspark.geotrellis.SpatialTiledRasterRDD.focal(TiledRasterRDD.scala:432)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jbouffard** [comment]
Both @jamesmcclain and I have faced this issue before. I'm not sure how he got around it, but I found deleting my `geotrellis/target` directory did the trick.
