### ISSUE TITLE
Better Error Handeling For bands() Method

### ISSUE THREAD

**Issue by jbouffard** [locationtech-labs/geopyspark#357]
There is a problem with the `bands` method where if the user selects a band that is out of range then a `py4j4` error will be thrown and not a normal Python exception. As mentioned in PR #329, the best way to handle this would be change what is returned in the Scala code so that way the error can be handled better.

**Comment by jbouffard** [comment]
@echeipesh There's an issue with your suggested method on error handling in #329. Because the method is being executed in Scala by Python in a `map`, any error that occurs during execution messes up the stream of bytes that gets returned to Python. Or a least, it appears to be that way. This causes an `EOFError` when bringing the results back to Python that immediately fails, and I have yet to find a way around.

This is the error that gets returned

```
17/07/17 13:09:06 ERROR PythonRunner: Python worker exited unexpectedly (crashed)
org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py", line 159, in main
    is_sql_udf = read_int(infile)
  File "/usr/local/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 577, in read_int
    raise EOFError
EOFError

	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:193)
	at org.apache.spark.api.python.PythonRunner$$anon$1.<init>(PythonRDD.scala:234)
	at org.apache.spark.api.python.PythonRunner.compute(PythonRDD.scala:152)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Band 3 does not exist
	at geotrellis.raster.ArrayMultibandTile.band(ArrayMultibandTile.scala:114)
	at geotrellis.raster.ArrayMultibandTile$$anonfun$subsetBands$1.apply$mcVI$sp(ArrayMultibandTile.scala:490)
	at geotrellis.raster.ArrayMultibandTile$$anonfun$subsetBands$1.apply(ArrayMultibandTile.scala:489)
	at geotrellis.raster.ArrayMultibandTile$$anonfun$subsetBands$1.apply(ArrayMultibandTile.scala:489)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at geotrellis.raster.ArrayMultibandTile.subsetBands(ArrayMultibandTile.scala:489)
	at geotrellis.raster.ArrayMultibandTile.subsetBands(ArrayMultibandTile.scala:90)
	at geotrellis.raster.MultibandTile$class.subsetBands(MultibandTile.scala:89)
	at geotrellis.raster.ArrayMultibandTile.subsetBands(ArrayMultibandTile.scala:90)
	at geopyspark.geotrellis.TiledRasterRDD$$anonfun$bands$1.apply(TiledRasterRDD.scala:62)
	at geopyspark.geotrellis.TiledRasterRDD$$anonfun$bands$1.apply(TiledRasterRDD.scala:62)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$mapValues$1$$anonfun$apply$43$$anonfun$apply$44.apply(PairRDDFunctions.scala:762)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$mapValues$1$$anonfun$apply$43$$anonfun$apply$44.apply(PairRDDFunctions.scala:762)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:504)
	at org.apache.spark.api.python.PythonRunner$WriterThread$$anonfun$run$3.apply(PythonRDD.scala:328)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1951)
	at org.apache.spark.api.python.PythonRunner$WriterThread.run(PythonRDD.scala:269)
17/07/17 13:09:06 ERROR PythonRunner: This may have been caused by a prior exception:
java.lang.IllegalArgumentException: Band 3 does not exist
	at geotrellis.raster.ArrayMultibandTile.band(ArrayMultibandTile.scala:114)
	at geotrellis.raster.ArrayMultibandTile$$anonfun$subsetBands$1.apply$mcVI$sp(ArrayMultibandTile.scala:490)
	at geotrellis.raster.ArrayMultibandTile$$anonfun$subsetBands$1.apply(ArrayMultibandTile.scala:489)
	at geotrellis.raster.ArrayMultibandTile$$anonfun$subsetBands$1.apply(ArrayMultibandTile.scala:489)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at geotrellis.raster.ArrayMultibandTile.subsetBands(ArrayMultibandTile.scala:489)
	at geotrellis.raster.ArrayMultibandTile.subsetBands(ArrayMultibandTile.scala:90)
	at geotrellis.raster.MultibandTile$class.subsetBands(MultibandTile.scala:89)
	at geotrellis.raster.ArrayMultibandTile.subsetBands(ArrayMultibandTile.scala:90)
	at geopyspark.geotrellis.TiledRasterRDD$$anonfun$bands$1.apply(TiledRasterRDD.scala:62)
	at geopyspark.geotrellis.TiledRasterRDD$$anonfun$bands$1.apply(TiledRasterRDD.scala:62)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$mapValues$1$$anonfun$apply$43$$anonfun$apply$44.apply(PairRDDFunctions.scala:762)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$mapValues$1$$anonfun$apply$43$$anonfun$apply$44.apply(PairRDDFunctions.scala:762)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:504)
	at org.apache.spark.api.python.PythonRunner$WriterThread$$anonfun$run$3.apply(PythonRDD.scala:328)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1951)
	at org.apache.spark.api.python.PythonRunner$WriterThread.run(PythonRDD.scala:269)
17/07/17 13:09:06 ERROR Executor: Exception in task 0.0 in stage 3.0 (TID 3)
java.lang.IllegalArgumentException: Band 3 does not exist
	at geotrellis.raster.ArrayMultibandTile.band(ArrayMultibandTile.scala:114)
	at geotrellis.raster.ArrayMultibandTile$$anonfun$subsetBands$1.apply$mcVI$sp(ArrayMultibandTile.scala:490)
	at geotrellis.raster.ArrayMultibandTile$$anonfun$subsetBands$1.apply(ArrayMultibandTile.scala:489)
	at geotrellis.raster.ArrayMultibandTile$$anonfun$subsetBands$1.apply(ArrayMultibandTile.scala:489)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at geotrellis.raster.ArrayMultibandTile.subsetBands(ArrayMultibandTile.scala:489)
	at geotrellis.raster.ArrayMultibandTile.subsetBands(ArrayMultibandTile.scala:90)
	at geotrellis.raster.MultibandTile$class.subsetBands(MultibandTile.scala:89)
	at geotrellis.raster.ArrayMultibandTile.subsetBands(ArrayMultibandTile.scala:90)
	at geopyspark.geotrellis.TiledRasterRDD$$anonfun$bands$1.apply(TiledRasterRDD.scala:62)
	at geopyspark.geotrellis.TiledRasterRDD$$anonfun$bands$1.apply(TiledRasterRDD.scala:62)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$mapValues$1$$anonfun$apply$43$$anonfun$apply$44.apply(PairRDDFunctions.scala:762)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$mapValues$1$$anonfun$apply$43$$anonfun$apply$44.apply(PairRDDFunctions.scala:762)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:504)
	at org.apache.spark.api.python.PythonRunner$WriterThread$$anonfun$run$3.apply(PythonRDD.scala:328)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1951)
	at org.apache.spark.api.python.PythonRunner$WriterThread.run(PythonRDD.scala:269)
17/07/17 13:09:06 WARN TaskSetManager: Lost task 0.0 in stage 3.0 (TID 3, localhost, executor driver): java.lang.IllegalArgumentException: Band 3 does not exist
	at geotrellis.raster.ArrayMultibandTile.band(ArrayMultibandTile.scala:114)
	at geotrellis.raster.ArrayMultibandTile$$anonfun$subsetBands$1.apply$mcVI$sp(ArrayMultibandTile.scala:490)
	at geotrellis.raster.ArrayMultibandTile$$anonfun$subsetBands$1.apply(ArrayMultibandTile.scala:489)
	at geotrellis.raster.ArrayMultibandTile$$anonfun$subsetBands$1.apply(ArrayMultibandTile.scala:489)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at geotrellis.raster.ArrayMultibandTile.subsetBands(ArrayMultibandTile.scala:489)
	at geotrellis.raster.ArrayMultibandTile.subsetBands(ArrayMultibandTile.scala:90)
	at geotrellis.raster.MultibandTile$class.subsetBands(MultibandTile.scala:89)
	at geotrellis.raster.ArrayMultibandTile.subsetBands(ArrayMultibandTile.scala:90)
	at geopyspark.geotrellis.TiledRasterRDD$$anonfun$bands$1.apply(TiledRasterRDD.scala:62)
	at geopyspark.geotrellis.TiledRasterRDD$$anonfun$bands$1.apply(TiledRasterRDD.scala:62)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$mapValues$1$$anonfun$apply$43$$anonfun$apply$44.apply(PairRDDFunctions.scala:762)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$mapValues$1$$anonfun$apply$43$$anonfun$apply$44.apply(PairRDDFunctions.scala:762)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:504)
	at org.apache.spark.api.python.PythonRunner$WriterThread$$anonfun$run$3.apply(PythonRDD.scala:328)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1951)
	at org.apache.spark.api.python.PythonRunner$WriterThread.run(PythonRDD.scala:269)
```

**Comment by jbouffard** [comment]
The only solution I came up with so far is to have the bands be selected in Python by bringing the `RDD` over and then be sent back to Scala similar to what is done in `map_tiles`. I'm not a big fan of it, but it would allow for better error handling.
