### ISSUE TITLE
Reading geopyspark pyramid layer after persisting to s3 throws Avro Error

### ISSUE THREAD

**Issue by jmelching** [locationtech-labs/geopyspark#507]
I have single band tiffs that i am trying to read from s3 and then writing the pyramid to s3 from inside geopyspark as below: 

`
layer = gps.geotiff.get(layer_type=gps.LayerType.SPATIAL,uri="s3://some.s3.payth/data/")
tiled_raster_layer = layer.tile_to_layout(gps.GlobalLayout(), target_crs=3857)
pyramid = tiled_raster_layer.repartition(100).pyramid()

for tiled_layer in pyramid.levels.values():
    gps.write(uri="s3://some.s3.path/catalog", layer_name="example-layer", tiled_raster_layer=tiled_layer)

tms_server = gps.TMS.build(("s3://some.s3.path/catalog", "example-layer"), 
                           display=yield_color_map)
M.add_layer(TMSRasterData(tms_server), name="example-layer")
`

When I try to read the layer back as above with the tms server I see the following stack.  I have tried using a Multiband Tiff, a SingleBandTiff, as well as a single file and multiple files as input.

`
[ERROR] [09/26/2017 04:29:50.287] [geopyspark-tile-server-akka.actor.default-dispatcher-5] [akka.actor.ActorSystemImpl(geopyspark-tile-server)] Error during processing of request HttpRequest(HttpMethod(GET),http://localhost:61799/tile/16/16045/24116.png,List(Host: localhost:61799, Connection: close, Accept-Encoding: gzip, Timeout-Access: <function1>),HttpEntity.Strict(none/none,ByteString()),HttpProtocol(HTTP/1.1))
org.apache.avro.AvroTypeException: Found geotrellis.raster.ArrayMultibandTile, expecting union. This can be caused by using a type parameter which doesn't match the object being deserialized.
	at geotrellis.spark.io.avro.AvroEncoder$.fromBinary(AvroEncoder.scala:94)
	at geotrellis.spark.io.avro.AvroEncoder$.fromBinary(AvroEncoder.scala:77)
	at geotrellis.spark.io.s3.S3ValueReader$$anon$1.read(S3ValueReader.scala:58)
	at geotrellis.spark.io.Reader$class.apply(Reader.scala:21)
	at geotrellis.spark.io.s3.S3ValueReader$$anon$1.apply(S3ValueReader.scala:39)
	at geopyspark.geotrellis.tms.TileReaders$CatalogTileReader$$anonfun$retrieve$1$$anonfun$5$$anonfun$apply$1.apply(TileReader.scala:59)
	at geopyspark.geotrellis.tms.TileReaders$CatalogTileReader$$anonfun$retrieve$1$$anonfun$5$$anonfun$apply$1.apply(TileReader.scala:59)
	at geopyspark.geotrellis.tms.TileReaders$.geopyspark$geotrellis$tms$TileReaders$$rezoom(TileReader.scala:32)
	at geopyspark.geotrellis.tms.TileReaders$CatalogTileReader$$anonfun$retrieve$1$$anonfun$5.apply(TileReader.scala:59)
	at geopyspark.geotrellis.tms.TileReaders$CatalogTileReader$$anonfun$retrieve$1$$anonfun$5.apply(TileReader.scala:59)
	at scala.util.Try$.apply(Try.scala:192)
	at geopyspark.geotrellis.tms.TileReaders$CatalogTileReader$$anonfun$retrieve$1.apply(TileReader.scala:59)
	at geopyspark.geotrellis.tms.TileReaders$CatalogTileReader$$anonfun$retrieve$1.apply(TileReader.scala:57)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
`

**Comment by jbouffard** [comment]
Hello, @jmelching. Thanks for submitting this issue. Could you post your code for the `yield_color_map` value? That could be the potential culprit as everything else looks correct.

**Comment by jmelching** [comment]
@jbouffard 
I don't think it is the colormap, as I am able to display this data without persisting it to s3 and just using the pyramid directly. I've included the color map, and the non-persisted display code below.

yield_breaks_dict = {150:0xB96230FF, 
                     170:0xDB9842FF, 
                     180:0xDFAC6CFF, 
                     190:0xE3C193FF, 
                     200:0xE6D6BEFF, 
                     210:0xE4E7C4FF, 
                     220:0xD9E2B2FF, 
                     230:0xBBCA7AFF, 
                     240:0x9EBD4DFF, 
                     300:0x569543FF}        

yield_color_map = gps.ColorMap.from_break_map(yield_breaks_dict)

tms_server = gps.TMS.build(pyramid, display=yield_color_map)
M.add_layer(TMSRasterData(tms_server), name="yield")

**Comment by jbouffard** [comment]
@jmelching Ah, okay. Yeah, your display code looks good to me. I'm going to see if I also run into that error. Would it be possible for you to send me one of the files that you were using?

**Comment by jmelching** [comment]
@jbouffard 
Can you try it with a tiff you have lying around, and if that doesn't work i'll figure out how to generate a sample input file that fails.  I have to anonymize the data a bit to share.

**Comment by jbouffard** [comment]
@jmelching 
I ran similar code and got the same error. I will continue to look into this issue throughout the day and will keep you updated on any developments that arise.

Thanks again for brining this issue to light!

**Comment by lossyrob** [comment]
An update, in case this wasn't communicated elsewhere: we store GeoPySpark ingested layers as MultibandTiles, even when those tiles only have one band. Our tms server currently expects single band Tiles. We need to modify the gps TMS server to handle both multiband and single band situations. We're looking into the best way to fix this.

A workaround for now is to do the ingest in Scala. Quite an oversight, thanks for pointing it out.

**Comment by jbouffard** [comment]
Another update, there is currently a PR up that resolves this issue, #508. There is no API changes/breaking in that PR, so none of your code or saved catalogs will need to be updated and/or altered. It will hopefully be merged in the next couple of days if not today. We then plan on releasing GeoPySpark v0.3.0 soon afterwards.
